name: Update Data
on:
  workflow_dispatch:
  schedule:
   - cron: '*/30 * * * *'

concurrency: ci-${{ github.ref }}

jobs:
  scan:
    name: Scan Data
    runs-on: ubuntu-latest
    env:
      RAYON_NUM_THREADS: "10"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Install xmllint
        run: sudo apt-get install -y unar ripgrep
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Set up cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - run: cargo build --release
      - run: cargo run --release -- run state.json --save --limit=10000 --sources=pypi,rubygems,hexpm
      - uses: EndBug/add-and-commit@v9
        with:
          add: '["state.json", "state-from-start.json", "keys/"]'
          # From https://github.community/t/github-actions-bot-email-address/17204/5
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          author_name: "commit-bot"
          message: "Update state"
          push: true
          pull: '--rebase --autostash'
